#' wandb_agent
#'
#' Will run a function or program with configuration parameters specified by server
#'
#' @param sweep_id (dict) Sweep ID generated by CLI or sweep API
#' @param func (func, optional) A function to call instead of the "program" specifed in the config.
#' @param entity (str, optional) W&B Entity
#' @param project (str, optional) W&B Project
#' @param count (int, optional) the number of trials to run.
#'
#' @return
#' @export
#'
#' @examples
wandb_agent <- function(sweep_id=NULL,func=NULL,entity=NULL,
                       project= NULL,count= NULL) {
  wandb$agent(sweep_id = sweep_id, func = func, entity = entity,
              project = project, count = count)
}
